[tool.poetry]
name = "machine-tools"
version = "0.2.07"
description = ""
authors = ["Andrey Nikolaevich Korenyuk <korenyuk.a.n@mail.ru>"]
readme = "README.md"
packages = [{include = "machine_tools_3"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.0.3"
dependency-injector = "^4.41.0"
service-for-my-projects = {git = "https://github.com/sad-engineer/service_for_my_projects.git"}
pydantic = "^2.11.3"
pydantic-settings = "^2.9.1"
black = "^25.1.0"
isort = "^6.0.1"
sqlalchemy = "^2.0.40"
alembic = "^1.15.2"
psycopg2 = "^2.9.10"
psycopg2-binary = "^2.9.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
init-machine-tools-db = "machine_tools_3.app.db.init_db:init_db_from_csv"