"""add new_column

Revision ID: 3d26531fb3ac
Revises: create_all_tables
Create Date: 2025-05-23 10:30:40.373177

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d26531fb3ac'
down_revision: Union[str, None] = 'create_all_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_tools', sa.Column('new_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine_tools', 'new_column')
    # ### end Alembic commands ###
