"""Initial migration

Revision ID: d82a528a633c
Revises:
Create Date: 2024-05-13 14:45:01.243

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d82a528a633c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("serial_number", sa.String(), nullable=True),
        sa.Column("spindle_power", sa.Float(), nullable=True),
        sa.Column("spindle_speed", sa.Integer(), nullable=True),
        sa.Column("table_size_x", sa.Float(), nullable=True),
        sa.Column("table_size_y", sa.Float(), nullable=True),
        sa.Column("table_size_z", sa.Float(), nullable=True),
        sa.Column("tool_count", sa.Integer(), nullable=True),
        sa.Column("control_system", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_machines_id"), "machines", ["id"], unique=False)
    op.create_index(op.f("ix_machines_name"), "machines", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_machines_name"), table_name="machines")
    op.drop_index(op.f("ix_machines_id"), table_name="machines")
    op.drop_table("machines")
    # ### end Alembic commands ###
